use pulumi_sdk::{Context, Input, Output, ResourceOptions, Result};
use std::collections::HashMap;

/// Input arguments for creating this resource.
///
/// Differentiated Services Code Point configuration for any given network interface
pub struct DscpConfigurationArgs {
    /// Destination IP ranges.
    pub destination_ip_ranges: Option<Vec<Input<network::v20240501::QosIpRangeArgs>>>,
    /// Destination port ranges.
    pub destination_port_ranges: Option<Vec<Input<network::v20240501::QosPortRangeArgs>>>,
    /// The name of the resource.
    pub dscp_configuration_name: Option<Input<String>>,
    /// Resource ID.
    pub id: Option<Input<String>>,
    /// Resource location.
    pub location: Option<Input<String>>,
    /// List of markings to be used in the configuration.
    pub markings: Option<Vec<Input<i64>>>,
    /// RNM supported protocol types.
    pub protocol: Option<Input<serde_json::Value>>,
    /// QoS object definitions
    pub qos_definition_collection: Option<Vec<Input<network::v20240501::QosDefinitionArgs>>>,
    /// The name of the resource group.
    pub resource_group_name: Input<String>,
    /// Source IP ranges.
    pub source_ip_ranges: Option<Vec<Input<network::v20240501::QosIpRangeArgs>>>,
    /// Sources port ranges.
    pub source_port_ranges: Option<Vec<Input<network::v20240501::QosPortRangeArgs>>>,
    /// Resource tags.
    pub tags: Option<HashMap<String, Input<String>>>,
}

/// Differentiated Services Code Point configuration for any given network interface
pub struct DscpConfiguration {
    /// The URN of this resource.
    pub urn: String,
    /// The provider-assigned unique ID.
    pub id: Output<serde_json::Value>,
    /// Associated Network Interfaces to the DSCP Configuration.
    pub associated_network_interfaces: Output<serde_json::Value>,
    /// The Azure API version of the resource.
    pub azure_api_version: Output<serde_json::Value>,
    /// Destination IP ranges.
    pub destination_ip_ranges: Output<serde_json::Value>,
    /// Destination port ranges.
    pub destination_port_ranges: Output<serde_json::Value>,
    /// A unique read-only string that changes whenever the resource is updated.
    pub etag: Output<serde_json::Value>,
    /// Resource location.
    pub location: Output<serde_json::Value>,
    /// List of markings to be used in the configuration.
    pub markings: Output<serde_json::Value>,
    /// Resource name.
    pub name: Output<serde_json::Value>,
    /// RNM supported protocol types.
    pub protocol: Output<serde_json::Value>,
    /// The provisioning state of the DSCP Configuration resource.
    pub provisioning_state: Output<serde_json::Value>,
    /// Qos Collection ID generated by RNM.
    pub qos_collection_id: Output<serde_json::Value>,
    /// QoS object definitions
    pub qos_definition_collection: Output<serde_json::Value>,
    /// The resource GUID property of the DSCP Configuration resource.
    pub resource_guid: Output<serde_json::Value>,
    /// Source IP ranges.
    pub source_ip_ranges: Output<serde_json::Value>,
    /// Sources port ranges.
    pub source_port_ranges: Output<serde_json::Value>,
    /// Resource tags.
    pub tags: Output<serde_json::Value>,
    /// Resource type.
    pub type_: Output<serde_json::Value>,
}

impl DscpConfiguration {
    const TYPE_TOKEN: &'static str = "azure-native:network/v20240501:DscpConfiguration";

    /// Create a new DscpConfiguration resource.
    pub async fn new(
        ctx: &Context,
        name: &str,
        args: DscpConfigurationArgs,
        opts: Option<ResourceOptions>,
    ) -> Result<Self> {
        let opts = opts.unwrap_or_default();
        let mut inputs = HashMap::new();
        let mut deps: Vec<String> = Vec::new();
        let mut prop_deps: HashMap<String, Vec<String>> = HashMap::new();

        if let Some(v) = args.destination_ip_ranges {
            pulumi_sdk::resolve_input_vec("destinationIpRanges", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.destination_port_ranges {
            pulumi_sdk::resolve_input_vec("destinationPortRanges", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.dscp_configuration_name {
            pulumi_sdk::resolve_input("dscpConfigurationName", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.id {
            pulumi_sdk::resolve_input("id", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.location {
            pulumi_sdk::resolve_input("location", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.markings {
            pulumi_sdk::resolve_input_vec("markings", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.protocol {
            pulumi_sdk::resolve_input("protocol", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.qos_definition_collection {
            pulumi_sdk::resolve_input_vec("qosDefinitionCollection", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        pulumi_sdk::resolve_input("resourceGroupName", args.resource_group_name, &mut inputs, &mut deps, &mut prop_deps).await;
        if let Some(v) = args.source_ip_ranges {
            pulumi_sdk::resolve_input_vec("sourceIpRanges", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.source_port_ranges {
            pulumi_sdk::resolve_input_vec("sourcePortRanges", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.tags {
            pulumi_sdk::resolve_input_map("tags", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }

        let registered = ctx.register_resource(
            Self::TYPE_TOKEN,
            name,
            inputs,
            prop_deps,
            &opts,
        ).await?;

        Ok(Self {
            urn: registered.urn.clone(),
            id: registered.outputs.get("id")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            associated_network_interfaces: registered.outputs.get("associatedNetworkInterfaces")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            azure_api_version: registered.outputs.get("azureApiVersion")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            destination_ip_ranges: registered.outputs.get("destinationIpRanges")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            destination_port_ranges: registered.outputs.get("destinationPortRanges")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            etag: registered.outputs.get("etag")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            location: registered.outputs.get("location")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            markings: registered.outputs.get("markings")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            name: registered.outputs.get("name")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            protocol: registered.outputs.get("protocol")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            provisioning_state: registered.outputs.get("provisioningState")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            qos_collection_id: registered.outputs.get("qosCollectionId")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            qos_definition_collection: registered.outputs.get("qosDefinitionCollection")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            resource_guid: registered.outputs.get("resourceGuid")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            source_ip_ranges: registered.outputs.get("sourceIpRanges")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            source_port_ranges: registered.outputs.get("sourcePortRanges")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            tags: registered.outputs.get("tags")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            type_: registered.outputs.get("type")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
        })
    }
}
