use pulumi_sdk::{Context, InvokeOptions, Result};
use serde_json::json;
use std::collections::HashMap;

/// Input arguments for this function.
///
/// List SSH authorized keys and shared key of the local user.
#[derive(Default)]
pub struct ListLocalUserKeysArgs {
    /// The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
    pub account_name: String,
    /// The name of the resource group within the user's subscription. The name is case insensitive.
    pub resource_group_name: String,
    /// The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
    pub username: String,
}

/// Result of the function invocation.
pub struct ListLocalUserKeysResult {
    /// Auto generated by the server for SMB authentication.
    pub shared_key: String,
    /// Optional, local user ssh authorized keys for SFTP.
    pub ssh_authorized_keys: Option<Vec<storage::v20240101::SshPublicKeyResponse>>,
}

/// List SSH authorized keys and shared key of the local user.
pub async fn list_local_user_keys(
    ctx: &Context,
    args: ListLocalUserKeysArgs,
    opts: Option<InvokeOptions>,
) -> Result<ListLocalUserKeysResult> {
    let mut invoke_args = HashMap::new();
    invoke_args.insert("accountName".to_string(), json!(args.account_name));
    invoke_args.insert("resourceGroupName".to_string(), json!(args.resource_group_name));
    invoke_args.insert("username".to_string(), json!(args.username));

    let opts = opts.unwrap_or_default();
    let result = ctx.invoke("azure-native:storage/v20240101:listLocalUserKeys", invoke_args, &opts).await?;

    Ok(ListLocalUserKeysResult {
        shared_key: serde_json::from_value(result.fields.get("sharedKey").cloned().unwrap_or_default())?
            ,
        ssh_authorized_keys: result.fields.get("sshAuthorizedKeys").cloned().map(serde_json::from_value).transpose()?,
    })
}
