/// Ssl cipher suites enums.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ApplicationGatewaySslCipherSuite {
    TLSECDHERSAWITHAES256CBCSHA384,
    TLSECDHERSAWITHAES128CBCSHA256,
    TLSECDHERSAWITHAES256CBCSHA,
    TLSECDHERSAWITHAES128CBCSHA,
    TLSDHERSAWITHAES256GCMSHA384,
    TLSDHERSAWITHAES128GCMSHA256,
    TLSDHERSAWITHAES256CBCSHA,
    TLSDHERSAWITHAES128CBCSHA,
    TLSRSAWITHAES256GCMSHA384,
    TLSRSAWITHAES128GCMSHA256,
    TLSRSAWITHAES256CBCSHA256,
    TLSRSAWITHAES128CBCSHA256,
    TLSRSAWITHAES256CBCSHA,
    TLSRSAWITHAES128CBCSHA,
    TLSECDHEECDSAWITHAES256GCMSHA384,
    TLSECDHEECDSAWITHAES128GCMSHA256,
    TLSECDHEECDSAWITHAES256CBCSHA384,
    TLSECDHEECDSAWITHAES128CBCSHA256,
    TLSECDHEECDSAWITHAES256CBCSHA,
    TLSECDHEECDSAWITHAES128CBCSHA,
    TLSDHEDSSWITHAES256CBCSHA256,
    TLSDHEDSSWITHAES128CBCSHA256,
    TLSDHEDSSWITHAES256CBCSHA,
    TLSDHEDSSWITHAES128CBCSHA,
    TLSRSAWITH3DESEDECBCSHA,
    TLSDHEDSSWITH3DESEDECBCSHA,
    TLSECDHERSAWITHAES128GCMSHA256,
    TLSECDHERSAWITHAES256GCMSHA384,
}

impl ApplicationGatewaySslCipherSuite {
    /// The wire value sent to the Pulumi engine.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::TLSECDHERSAWITHAES256CBCSHA384 => "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
            Self::TLSECDHERSAWITHAES128CBCSHA256 => "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
            Self::TLSECDHERSAWITHAES256CBCSHA => "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
            Self::TLSECDHERSAWITHAES128CBCSHA => "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
            Self::TLSDHERSAWITHAES256GCMSHA384 => "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
            Self::TLSDHERSAWITHAES128GCMSHA256 => "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
            Self::TLSDHERSAWITHAES256CBCSHA => "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
            Self::TLSDHERSAWITHAES128CBCSHA => "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
            Self::TLSRSAWITHAES256GCMSHA384 => "TLS_RSA_WITH_AES_256_GCM_SHA384",
            Self::TLSRSAWITHAES128GCMSHA256 => "TLS_RSA_WITH_AES_128_GCM_SHA256",
            Self::TLSRSAWITHAES256CBCSHA256 => "TLS_RSA_WITH_AES_256_CBC_SHA256",
            Self::TLSRSAWITHAES128CBCSHA256 => "TLS_RSA_WITH_AES_128_CBC_SHA256",
            Self::TLSRSAWITHAES256CBCSHA => "TLS_RSA_WITH_AES_256_CBC_SHA",
            Self::TLSRSAWITHAES128CBCSHA => "TLS_RSA_WITH_AES_128_CBC_SHA",
            Self::TLSECDHEECDSAWITHAES256GCMSHA384 => "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            Self::TLSECDHEECDSAWITHAES128GCMSHA256 => "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            Self::TLSECDHEECDSAWITHAES256CBCSHA384 => "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
            Self::TLSECDHEECDSAWITHAES128CBCSHA256 => "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
            Self::TLSECDHEECDSAWITHAES256CBCSHA => "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
            Self::TLSECDHEECDSAWITHAES128CBCSHA => "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
            Self::TLSDHEDSSWITHAES256CBCSHA256 => "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256",
            Self::TLSDHEDSSWITHAES128CBCSHA256 => "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256",
            Self::TLSDHEDSSWITHAES256CBCSHA => "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",
            Self::TLSDHEDSSWITHAES128CBCSHA => "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
            Self::TLSRSAWITH3DESEDECBCSHA => "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            Self::TLSDHEDSSWITH3DESEDECBCSHA => "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA",
            Self::TLSECDHERSAWITHAES128GCMSHA256 => "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            Self::TLSECDHERSAWITHAES256GCMSHA384 => "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        }
    }
}

impl From<ApplicationGatewaySslCipherSuite> for serde_json::Value {
    fn from(v: ApplicationGatewaySslCipherSuite) -> Self {
        serde_json::Value::String(v.as_str().to_string())
    }
}

impl serde::Serialize for ApplicationGatewaySslCipherSuite {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for ApplicationGatewaySslCipherSuite {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> std::result::Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        match s.as_str() {
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384" => Ok(Self::TLSECDHERSAWITHAES256CBCSHA384),
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256" => Ok(Self::TLSECDHERSAWITHAES128CBCSHA256),
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" => Ok(Self::TLSECDHERSAWITHAES256CBCSHA),
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA" => Ok(Self::TLSECDHERSAWITHAES128CBCSHA),
            "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384" => Ok(Self::TLSDHERSAWITHAES256GCMSHA384),
            "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256" => Ok(Self::TLSDHERSAWITHAES128GCMSHA256),
            "TLS_DHE_RSA_WITH_AES_256_CBC_SHA" => Ok(Self::TLSDHERSAWITHAES256CBCSHA),
            "TLS_DHE_RSA_WITH_AES_128_CBC_SHA" => Ok(Self::TLSDHERSAWITHAES128CBCSHA),
            "TLS_RSA_WITH_AES_256_GCM_SHA384" => Ok(Self::TLSRSAWITHAES256GCMSHA384),
            "TLS_RSA_WITH_AES_128_GCM_SHA256" => Ok(Self::TLSRSAWITHAES128GCMSHA256),
            "TLS_RSA_WITH_AES_256_CBC_SHA256" => Ok(Self::TLSRSAWITHAES256CBCSHA256),
            "TLS_RSA_WITH_AES_128_CBC_SHA256" => Ok(Self::TLSRSAWITHAES128CBCSHA256),
            "TLS_RSA_WITH_AES_256_CBC_SHA" => Ok(Self::TLSRSAWITHAES256CBCSHA),
            "TLS_RSA_WITH_AES_128_CBC_SHA" => Ok(Self::TLSRSAWITHAES128CBCSHA),
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384" => Ok(Self::TLSECDHEECDSAWITHAES256GCMSHA384),
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256" => Ok(Self::TLSECDHEECDSAWITHAES128GCMSHA256),
            "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384" => Ok(Self::TLSECDHEECDSAWITHAES256CBCSHA384),
            "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256" => Ok(Self::TLSECDHEECDSAWITHAES128CBCSHA256),
            "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA" => Ok(Self::TLSECDHEECDSAWITHAES256CBCSHA),
            "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA" => Ok(Self::TLSECDHEECDSAWITHAES128CBCSHA),
            "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256" => Ok(Self::TLSDHEDSSWITHAES256CBCSHA256),
            "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256" => Ok(Self::TLSDHEDSSWITHAES128CBCSHA256),
            "TLS_DHE_DSS_WITH_AES_256_CBC_SHA" => Ok(Self::TLSDHEDSSWITHAES256CBCSHA),
            "TLS_DHE_DSS_WITH_AES_128_CBC_SHA" => Ok(Self::TLSDHEDSSWITHAES128CBCSHA),
            "TLS_RSA_WITH_3DES_EDE_CBC_SHA" => Ok(Self::TLSRSAWITH3DESEDECBCSHA),
            "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA" => Ok(Self::TLSDHEDSSWITH3DESEDECBCSHA),
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" => Ok(Self::TLSECDHERSAWITHAES128GCMSHA256),
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" => Ok(Self::TLSECDHERSAWITHAES256GCMSHA384),
            _ => Err(serde::de::Error::unknown_variant(&s, &["TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_DHE_RSA_WITH_AES_256_CBC_SHA", "TLS_DHE_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_GCM_SHA256", "TLS_RSA_WITH_AES_256_CBC_SHA256", "TLS_RSA_WITH_AES_128_CBC_SHA256", "TLS_RSA_WITH_AES_256_CBC_SHA", "TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256", "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256", "TLS_DHE_DSS_WITH_AES_256_CBC_SHA", "TLS_DHE_DSS_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"])),
        }
    }
}
