use pulumi_sdk::{Context, InvokeOptions, Result};
use serde_json::json;
use std::collections::HashMap;

/// Input arguments for this function.
///
/// Gets a DSCP Configuration.
#[derive(Default)]
pub struct GetDscpConfigurationArgs {
    /// The name of the resource.
    pub dscp_configuration_name: String,
    /// The name of the resource group.
    pub resource_group_name: String,
}

/// Result of the function invocation.
pub struct GetDscpConfigurationResult {
    /// Associated Network Interfaces to the DSCP Configuration.
    pub associated_network_interfaces: Vec<network::v20210801::NetworkInterfaceResponse>,
    /// The Azure API version of the resource.
    pub azure_api_version: String,
    /// Destination IP ranges.
    pub destination_ip_ranges: Option<Vec<network::v20210801::QosIpRangeResponse>>,
    /// Destination port ranges.
    pub destination_port_ranges: Option<Vec<network::v20210801::QosPortRangeResponse>>,
    /// A unique read-only string that changes whenever the resource is updated.
    pub etag: String,
    /// Resource ID.
    pub id: Option<String>,
    /// Resource location.
    pub location: Option<String>,
    /// List of markings to be used in the configuration.
    pub markings: Option<Vec<i64>>,
    /// Resource name.
    pub name: String,
    /// RNM supported protocol types.
    pub protocol: Option<String>,
    /// The provisioning state of the DSCP Configuration resource.
    pub provisioning_state: String,
    /// Qos Collection ID generated by RNM.
    pub qos_collection_id: String,
    /// QoS object definitions
    pub qos_definition_collection: Option<Vec<network::v20210801::QosDefinitionResponse>>,
    /// The resource GUID property of the DSCP Configuration resource.
    pub resource_guid: String,
    /// Source IP ranges.
    pub source_ip_ranges: Option<Vec<network::v20210801::QosIpRangeResponse>>,
    /// Sources port ranges.
    pub source_port_ranges: Option<Vec<network::v20210801::QosPortRangeResponse>>,
    /// Resource tags.
    pub tags: Option<HashMap<String, String>>,
    /// Resource type.
    pub type_: String,
}

/// Gets a DSCP Configuration.
pub async fn get_dscp_configuration(
    ctx: &Context,
    args: GetDscpConfigurationArgs,
    opts: Option<InvokeOptions>,
) -> Result<GetDscpConfigurationResult> {
    let mut invoke_args = HashMap::new();
    invoke_args.insert("dscpConfigurationName".to_string(), json!(args.dscp_configuration_name));
    invoke_args.insert("resourceGroupName".to_string(), json!(args.resource_group_name));

    let opts = opts.unwrap_or_default();
    let result = ctx.invoke("azure-native:network/v20210801:getDscpConfiguration", invoke_args, &opts).await?;

    Ok(GetDscpConfigurationResult {
        associated_network_interfaces: serde_json::from_value(result.fields.get("associatedNetworkInterfaces").cloned().unwrap_or_default())?
            ,
        azure_api_version: serde_json::from_value(result.fields.get("azureApiVersion").cloned().unwrap_or_default())?
            ,
        destination_ip_ranges: result.fields.get("destinationIpRanges").cloned().map(serde_json::from_value).transpose()?,
        destination_port_ranges: result.fields.get("destinationPortRanges").cloned().map(serde_json::from_value).transpose()?,
        etag: serde_json::from_value(result.fields.get("etag").cloned().unwrap_or_default())?
            ,
        id: result.fields.get("id").cloned().map(serde_json::from_value).transpose()?,
        location: result.fields.get("location").cloned().map(serde_json::from_value).transpose()?,
        markings: result.fields.get("markings").cloned().map(serde_json::from_value).transpose()?,
        name: serde_json::from_value(result.fields.get("name").cloned().unwrap_or_default())?
            ,
        protocol: result.fields.get("protocol").cloned().map(serde_json::from_value).transpose()?,
        provisioning_state: serde_json::from_value(result.fields.get("provisioningState").cloned().unwrap_or_default())?
            ,
        qos_collection_id: serde_json::from_value(result.fields.get("qosCollectionId").cloned().unwrap_or_default())?
            ,
        qos_definition_collection: result.fields.get("qosDefinitionCollection").cloned().map(serde_json::from_value).transpose()?,
        resource_guid: serde_json::from_value(result.fields.get("resourceGuid").cloned().unwrap_or_default())?
            ,
        source_ip_ranges: result.fields.get("sourceIpRanges").cloned().map(serde_json::from_value).transpose()?,
        source_port_ranges: result.fields.get("sourcePortRanges").cloned().map(serde_json::from_value).transpose()?,
        tags: result.fields.get("tags").cloned().map(serde_json::from_value).transpose()?,
        type_: serde_json::from_value(result.fields.get("type").cloned().unwrap_or_default())?
            ,
    })
}
