use pulumi_sdk::{Context, InvokeOptions, Result};
use serde_json::json;
use std::collections::HashMap;

/// Input arguments for this function.
///
/// Get the local user of the storage account by username.
#[derive(Default)]
pub struct GetLocalUserArgs {
    /// The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
    pub account_name: String,
    /// The name of the resource group within the user's subscription. The name is case insensitive.
    pub resource_group_name: String,
    /// The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
    pub username: String,
}

/// Result of the function invocation.
pub struct GetLocalUserResult {
    /// The Azure API version of the resource.
    pub azure_api_version: String,
    /// Indicates whether shared key exists. Set it to false to remove existing shared key.
    pub has_shared_key: Option<bool>,
    /// Indicates whether ssh key exists. Set it to false to remove existing SSH key.
    pub has_ssh_key: Option<bool>,
    /// Indicates whether ssh password exists. Set it to false to remove existing SSH password.
    pub has_ssh_password: Option<bool>,
    /// Optional, local user home directory.
    pub home_directory: Option<String>,
    /// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
    pub id: String,
    /// The name of the resource
    pub name: String,
    /// The permission scopes of the local user.
    pub permission_scopes: Option<Vec<storage::v20230101::PermissionScopeResponse>>,
    /// A unique Security Identifier that is generated by the server.
    pub sid: String,
    /// Optional, local user ssh authorized keys for SFTP.
    pub ssh_authorized_keys: Option<Vec<storage::v20230101::SshPublicKeyResponse>>,
    /// Metadata pertaining to creation and last modification of the resource.
    pub system_data: storage::v20230101::SystemDataResponse,
    /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
    pub type_: String,
}

/// Get the local user of the storage account by username.
pub async fn get_local_user(
    ctx: &Context,
    args: GetLocalUserArgs,
    opts: Option<InvokeOptions>,
) -> Result<GetLocalUserResult> {
    let mut invoke_args = HashMap::new();
    invoke_args.insert("accountName".to_string(), json!(args.account_name));
    invoke_args.insert("resourceGroupName".to_string(), json!(args.resource_group_name));
    invoke_args.insert("username".to_string(), json!(args.username));

    let opts = opts.unwrap_or_default();
    let result = ctx.invoke("azure-native:storage/v20230101:getLocalUser", invoke_args, &opts).await?;

    Ok(GetLocalUserResult {
        azure_api_version: serde_json::from_value(result.fields.get("azureApiVersion").cloned().unwrap_or_default())?
            ,
        has_shared_key: result.fields.get("hasSharedKey").cloned().map(serde_json::from_value).transpose()?,
        has_ssh_key: result.fields.get("hasSshKey").cloned().map(serde_json::from_value).transpose()?,
        has_ssh_password: result.fields.get("hasSshPassword").cloned().map(serde_json::from_value).transpose()?,
        home_directory: result.fields.get("homeDirectory").cloned().map(serde_json::from_value).transpose()?,
        id: serde_json::from_value(result.fields.get("id").cloned().unwrap_or_default())?
            ,
        name: serde_json::from_value(result.fields.get("name").cloned().unwrap_or_default())?
            ,
        permission_scopes: result.fields.get("permissionScopes").cloned().map(serde_json::from_value).transpose()?,
        sid: serde_json::from_value(result.fields.get("sid").cloned().unwrap_or_default())?
            ,
        ssh_authorized_keys: result.fields.get("sshAuthorizedKeys").cloned().map(serde_json::from_value).transpose()?,
        system_data: serde_json::from_value(result.fields.get("systemData").cloned().unwrap_or_default())?
            ,
        type_: serde_json::from_value(result.fields.get("type").cloned().unwrap_or_default())?
            ,
    })
}
