use pulumi_sdk::{Context, Input, Output, ResourceOptions, Result};
use std::collections::HashMap;

/// Input arguments for creating this resource.
///
/// The local user associated with the storage accounts.
pub struct LocalUserArgs {
    /// The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
    pub account_name: Input<String>,
    /// Indicates whether shared key exists. Set it to false to remove existing shared key.
    pub has_shared_key: Option<Input<bool>>,
    /// Indicates whether ssh key exists. Set it to false to remove existing SSH key.
    pub has_ssh_key: Option<Input<bool>>,
    /// Indicates whether ssh password exists. Set it to false to remove existing SSH password.
    pub has_ssh_password: Option<Input<bool>>,
    /// Optional, local user home directory.
    pub home_directory: Option<Input<String>>,
    /// The permission scopes of the local user.
    pub permission_scopes: Option<Vec<Input<storage::v20230401::PermissionScopeArgs>>>,
    /// The name of the resource group within the user's subscription. The name is case insensitive.
    pub resource_group_name: Input<String>,
    /// Optional, local user ssh authorized keys for SFTP.
    pub ssh_authorized_keys: Option<Vec<Input<storage::v20230401::SshPublicKeyArgs>>>,
    /// The name of local user. The username must contain lowercase letters and numbers only. It must be unique only within the storage account.
    pub username: Option<Input<String>>,
}

/// The local user associated with the storage accounts.
pub struct LocalUser {
    /// The URN of this resource.
    pub urn: String,
    /// The provider-assigned unique ID.
    pub id: Output<serde_json::Value>,
    /// The Azure API version of the resource.
    pub azure_api_version: Output<serde_json::Value>,
    /// Indicates whether shared key exists. Set it to false to remove existing shared key.
    pub has_shared_key: Output<serde_json::Value>,
    /// Indicates whether ssh key exists. Set it to false to remove existing SSH key.
    pub has_ssh_key: Output<serde_json::Value>,
    /// Indicates whether ssh password exists. Set it to false to remove existing SSH password.
    pub has_ssh_password: Output<serde_json::Value>,
    /// Optional, local user home directory.
    pub home_directory: Output<serde_json::Value>,
    /// The name of the resource
    pub name: Output<serde_json::Value>,
    /// The permission scopes of the local user.
    pub permission_scopes: Output<serde_json::Value>,
    /// A unique Security Identifier that is generated by the server.
    pub sid: Output<serde_json::Value>,
    /// Optional, local user ssh authorized keys for SFTP.
    pub ssh_authorized_keys: Output<serde_json::Value>,
    /// Metadata pertaining to creation and last modification of the resource.
    pub system_data: Output<serde_json::Value>,
    /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
    pub type_: Output<serde_json::Value>,
}

impl LocalUser {
    const TYPE_TOKEN: &'static str = "azure-native:storage/v20230401:LocalUser";

    /// Create a new LocalUser resource.
    pub async fn new(
        ctx: &Context,
        name: &str,
        args: LocalUserArgs,
        opts: Option<ResourceOptions>,
    ) -> Result<Self> {
        let opts = opts.unwrap_or_default();
        let mut inputs = HashMap::new();
        let mut deps: Vec<String> = Vec::new();
        let mut prop_deps: HashMap<String, Vec<String>> = HashMap::new();

        pulumi_sdk::resolve_input("accountName", args.account_name, &mut inputs, &mut deps, &mut prop_deps).await;
        if let Some(v) = args.has_shared_key {
            pulumi_sdk::resolve_input("hasSharedKey", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.has_ssh_key {
            pulumi_sdk::resolve_input("hasSshKey", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.has_ssh_password {
            pulumi_sdk::resolve_input("hasSshPassword", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.home_directory {
            pulumi_sdk::resolve_input("homeDirectory", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.permission_scopes {
            pulumi_sdk::resolve_input_vec("permissionScopes", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        pulumi_sdk::resolve_input("resourceGroupName", args.resource_group_name, &mut inputs, &mut deps, &mut prop_deps).await;
        if let Some(v) = args.ssh_authorized_keys {
            pulumi_sdk::resolve_input_vec("sshAuthorizedKeys", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }
        if let Some(v) = args.username {
            pulumi_sdk::resolve_input("username", v, &mut inputs, &mut deps, &mut prop_deps).await;
        }

        let registered = ctx.register_resource(
            Self::TYPE_TOKEN,
            name,
            inputs,
            prop_deps,
            &opts,
        ).await?;

        Ok(Self {
            urn: registered.urn.clone(),
            id: registered.outputs.get("id")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            azure_api_version: registered.outputs.get("azureApiVersion")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            has_shared_key: registered.outputs.get("hasSharedKey")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            has_ssh_key: registered.outputs.get("hasSshKey")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            has_ssh_password: registered.outputs.get("hasSshPassword")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            home_directory: registered.outputs.get("homeDirectory")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            name: registered.outputs.get("name")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            permission_scopes: registered.outputs.get("permissionScopes")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            sid: registered.outputs.get("sid")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            ssh_authorized_keys: registered.outputs.get("sshAuthorizedKeys")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            system_data: registered.outputs.get("systemData")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
            type_: registered.outputs.get("type")
                .cloned()
                .unwrap_or_else(|| Output::unknown(vec![registered.urn.clone()])),
        })
    }
}
